# Generated by Django 4.1.7 on 2023-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_phone',
            new_name='order_phone',
        ),
    ]
